//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Crud_NET.Models
{
        
    public partial class Funcionario
    {
        public int FuncionarioId { get; set; }

        public string Nome { get; set; }

        public string Cargo { get; set; }

        public string Email { get; set; }
    }
}
